#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 12 15:48:52 2021

@author: quangkhanh
"""
from sentence_transformers import SentenceTransformer
from sklearn.mixture import GaussianMixture
from tqdm import tqdm 
import numpy as np
import pandas as pd
import pickle 

model = SentenceTransformer('stsb-xlm-r-multilingual')
messages = pd.read_csv("data/shop_questions.csv").sample(frac=1)
n_sample = messages.shape[0]

def to_vector(messages, n_sample): 
    data = []
    
    for i in tqdm (range(n_sample), desc="Loading..."): 
        data.append(model.encode(messages.at[i, "message"]))
        
    return np.array(data)

data = to_vector(messages, n_sample)
# pickle.dump(data, open("data/message_vectors.plk", "wb"))

#%% 

n_cluster = 4

gm = GaussianMixture(n_components=n_cluster, random_state=0)
gm.fit(data) 

labels = gm.predict(data)

df = pd.DataFrame({"message": messages["message"][:n_sample], "cluster": labels})
# df.to_csv("data/message_cluster.csv", index=False)
# pickle.dump(gm, open("model/shop_message_gmm.pkl", "wb"))

df6 = df[df.cluster == 6]
df5 = df[df.cluster == 5]
df4 = df[df.cluster == 4]
df3 = df[df.cluster == 3]
df2 = df[df.cluster == 2]
df1 = df[df.cluster == 1]
df0 = df[df.cluster == 0]