#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 14 15:29:27 2021

@author: quangkhanh
"""

from src.miner.extractor import * 
from src.miner.factory import *
from src.miner.hasher import *

import pandas as pd

nh = NodeHasher()
eh = EdgeHasher(nh)
gh = GraphHasher(nh, eh)
gf = UserGraphFactory(gh)
ef = UserEdgeFactory(eh)
nf = UserNodeFactory()
gfe = GraphFrequencyExtractor(gf, ef, nf, gh)
fe = FlowExtractor()
flows = fe.extract("data/actions.csv")
super_flows = []
for flow in flows:
    super_flows.extend(fe.extract_sub_flow(flow))
result = gfe.extract(super_flows)
frequency = result[0]
df1 = pd.DataFrame(
    {"graph": frequency.keys(),
     "frequency": frequency.values()
     }
    )