#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 22 15:18:01 2021

@author: quangkhanh
"""

import pandas as pd
from tqdm import tqdm

onenet_model_path = "model/denver-onenet.tar.gz"

from denver.learners import OnenetLearner
learn = OnenetLearner(mode='inference', 
                      model_path=onenet_model_path)

i = 0
def transform_to_action(x): 
    global i
    i += 1
    if str(x) == "nan": 
        return ""
    else:
        try: 
            result = learn.predict(sample=x)
            return result["intent"]
        except: 
            print(x, i)
            return "UNKNOWN"

df = pd.read_csv("data/all_chatlog_2020_5d.csv")
df["user_action"] = df.user_message.apply(transform_to_action)
#%%
from tqdm import tqdm
shop_id = 1059845080701224

new_df = df.copy()
n_row = new_df.shape[0]

for i in tqdm(range(n_row), desc="Processing"):
    if str(new_df.at[i, "attachments"]) != "nan":
        if new_df.at[i, "attachments"].startswith("https://sco"): 
            object_sent = "send_image"
        else: 
            object_sent = "sent_gif"
        if new_df.at[i,"sender_id"] == shop_id: 
            new_df.at[i,"shop_message"] = object_sent 
        else: 
            new_df.at[i,"user_action"] = object_sent
            
            
new_df.to_csv("data/user_actions.csv", index=False)