#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb  1 11:41:22 2021

@author: quangkhanh
"""

from src.miner.extractor import FlowExtractor, UniqueFrequentFlowExtractor
from src.miner.hasher import FlowHasher

import pandas as pd

data_path = "data/actions.csv"

flow_extractor = FlowExtractor()
flow_hasher = FlowHasher()
unique_frequent_flow_extractor = UniqueFrequentFlowExtractor \
    .Builder() \
        .set_min_proportion(0.02) \
            .build()

#%%
flows = flow_extractor.extract(data_path)
result = unique_frequent_flow_extractor.extract(flows)

df = pd.DataFrame({"pattern": [flow_hasher.hash(k) for k in result.keys()],
                   "frequency": result.values()}).sort_values(by="frequency", 
                                                              ascending=False)