#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 25 13:48:45 2021

@author: quangkhanh
"""
from src.scripts.graph_analysis.base_entity import *

#%% 
flows = flow_extractor.extract("data/actions.csv")
result = unique_graph_extractor.extract(flows)
pattern_names = [graph_hasher.hash(p) for p in result.keys()]
patterns = pd.DataFrame({"pattern": pattern_names, "frequency": result.values()})
patterns
patterns.to_csv("data/patterns.csv")


